### ISSUE TITLE
rapuma system setup

### ISSUE THREAD

**Issue by Steven-Harris** [sillsdev/rapuma#1]
I tried running the following line to setup my rapuma project

```
rapuma system setup projects -s "~/Publishing"
```

and I received the following error

```
ERROR: Command not supported. Process halting.
```

**Comment by thresherdj** [comment]
Hi Steven,

It is unclear to me as to why this is not working. However, I would have 
to say that using the master branch is going to be problematic. Because 
of issues in the CLI I developed another branch that is being used for 
production. I've been using that branch now for almost a year. I could 
help you better if you were using that branch. However, I don't know 
where you are coming from. Are you trying to typeset Scripture or is 
this a school project? If it is the latter, then you probably need to 
stay with the master branch of the repo. My time is very limited but 
I'll help any way I can, what are you wanting to do?

Thanks,

Dennis

**Comment by Steven-Harris** [comment]
Hi Dennis, 

Yes, I am working with the SIL student project. The essence of our project is to wrap rapuma in a web interface. The above error occurred when using the master branch and your personal one. We might not be setting up something right but we are having trouble understanding and debugging the issue...

I have been able to render a sample document that Campbell prince gave us. I place the folder he gave us into /var/lib/rapuma/publishing and ran the render helperscript with no problems. Now we are trying to learn how to set up the project/folder from scratch and are having a lot of errors. 

 If you want to see how we are installing Rapuma, you can look at the ansible installer we have at https://github.com/sil-student-projects/web-scriptureforge/tree/master-sbu/deploy . 

Thanks for helping us out,

Steven

**Comment by thresherdj** [comment]
Hi Steven,

Good to meet you!

First, let me say that there is a vast difference between the master and 
my personal branch. There were some issues that needed to be addressed 
which required rewriting the Rapuma CLI. That is what is in my personal 
branch and it is what is being used for the little bit of production 
that is being done with the system now. I would really prefer that the 
new CLI be used but I know that for the sake of the work you are doing, 
Cambell would want you to use the master branch. So, be sure that you 
don't use my personal branch, the CLI isn't even close to the master branch.

So, any how, I looked over the main rapuma script (rapuma/scripts) and 
found a typo in the code for the command you are having a problem with. 
I updated the master branch of the repo so if you pull that, and install 
it, it should work for you. Let me know if this doesn't or you need 
anything else.

Blessings,

Dennis

**Comment by Steven-Harris** [comment]
That fixed the problem! Thank you so much for your time Dennis
