### ISSUE TITLE
Basic functionality and rendering problems

### ISSUE THREAD

**Issue by Steven-Harris** [sillsdev/rapuma#2]
Hi,

I am having a lot of difficulty understanding what rapuma commands to use to setup a project and render some basic documents. I feel I don't understand how the commands are structured together and what commands are needed before others. 

My goal is to render a mat.usfm file that I have. I believe once I set everything up I can run the following command

```
 rapuma group MAT GOSPEL group render
```

Although right now I get nothing but errors.

I have tried to create the group and add components to the group running this command.

```
rapuma group MAT NT group add --source_path Component/mat/mat.usfm
```

But no matter what I try for the source path I get errors like this: 
`Must provide a source path or valid component IDs to add a group. Process halting.` 
or this 
`Components not found: [mrklukjhnactrom1co2cogalephphpcol1th2th1ti2tititphmhebjas1pe2pe1jn2jn3jnjudrev] Process halting.`

Honestly, I am pretty lost with the control and if you could help me get started, it would be greatly appreciated.

Thanks,

Steven Harris

**Comment by thresherdj** [comment]
Hi Steve,

Sorry for the problems you are having. I wish you could be using the 
updated CLI which is more intuitive. However, in lieu of that, one thing 
that might be causing this is the path you are using. Projects I work 
with are normally in my home directory. From what I understand, your 
projects are buried in the system some where. I think it is failing with 
--source_path as it can't find Component/mat/.mat.usfm. I would try 
giving that a full path starting with root and see what happens. Also, 
this version of rapuma already knows the names of the files it wants. 
(This is because you specify the file type, see below.) For example, if 
you are adding the mat component, it will be looking for mat.usfm. 
Therefore, remove the file name from the source path specifier.

A second thing that I think is happening is that you need to specify the 
component being added. There was some kind of automation that would add 
all the components in a group like NT which would be mat through rev but 
in this case, you are trying to add just one component so you will need 
to specify what component you are adding. If you type "rapuma group -h" 
you will see this near the bottom of the output:

-i CID_LIST, --cid_list CID_LIST
                         Using the proper ID, specify components to be 
added to
                         this group. A group can have one or more 
components.
                         The list must be enclosed by quotes and have only a
                         space between ID codes, e.g. "aaa bbb ccc".

The -h command will give you clues. I realize the interface is not 
intuitive (and that's why I rewrote it) but using help will help you 
figure out what you need to know.

A third thing I see is that the type is missing. When creating a group, 
you need to specify the type. Again, -h tells you this:

-t {usfm,pdf}, --component_type {usfm,pdf}
                         The group component type is needed for creating 
a new
                         group.

In your case you want to use the "usfm" type.

Understanding these things, try running the command like this:

rapuma group MAT GOSPEL group add --component_type usfm --cid_list mat 
-- <full path without file name>

If all the books of the Gospel were in the source folder and you wanted 
to add them all at once, you would express the command like this:

rapuma group MAT GOSPEL group add --component_type usfm --cid_list "mat 
mrk luk jhn" -- <full path without file name>

Rapuma would then go to the specified source folder and look for 
mat.usfm, mrk.usfm, luk.usfm and jhn.usfm, then import them into the 
project. But if that were the case, you might want to use a different 
project name than MAT as that would be misleading.

So, try that and let me know how it goes.

Thanks,

Dennis

**Comment by Steven-Harris** [comment]
Hey dennis, thank you for your continual help! I am still having issues, so let me good everything from the top... I am going to go into a lot of unnecessary detail, but I am hoping that will help pinpoint the problem.

### A little bit of background
Users of our project will work on one book at a time and we want rapuma to render the book that we specify.  So, our I idea would be to only have one book in each project in order to only render the book of the bible the person typesetting is working on.

### My folder structure 
The file I need to render is located in my documents folder ~/Documents/mat/. It is just a sample usfm doc I have. You can find it below. Note that the file type I am using is usfm but change it to txt for GitHub.
[mat.txt](https://github.com/sillsdev/rapuma/files/93593/mat.txt)

I made a folder to render projects out of at ~/src/web-scriptureforge/Publishing

### Project Setup & Errors
I started from the beginning and setup the username and id
```rapuma system setup name -s "steven"```
```rapuma system setup uid -s 001```

Then I setup the publishing projects folder
```rapuma system setup projects -s "~/src/web-scriptureforge/Publishing"```

###### (sweet, no errors yet!)

### Adding component 
I start by using the command you gave me with a slight change of "-s" where the "--" is

**Comment by thresherdj** [comment]
Hi Steve, thanks for the explanation but I think the message got cut off 
or something. What I have quoted below is the last couple lines of what 
I got in your message. What's up with that? Is Git truncating the 
message or did you just send it prematurely?

Dennis

On 01/17/2016 02:48 PM, Steven Harris wrote:

...

**Comment by Steven-Harris** [comment]
Oh! Yes I was in the process of writing you back and I accidentally submit it. However, I was able to get it working so I deleted the comment. Now I messing around with the functionality. 

I had one question. If I change the value in the adjustment.config to be %1.2 = 3. Is the supposed to change the growth factor of chapter 1 verse 3 to 3?

**Comment by thresherdj** [comment]
Hey Steven,

First, know that the "%" character in this context is for commenting a 
line out. So if I have this:

[mat]
     [[mat]]
         1.2 = 3

What should happen is that verse 2 (actually the entire paragraph) of 
chapter one will be stretched by 3 lines. Realistically, TeX, the 
rendering engine will not let that happen, and if it did, it would look 
really ugly. Normally we will not add more than a line (1.2 = 1) to any 
given paragraph if it is a reasonable thing to do. We can even tell the 
rendering engine to take out a line with -1 but that seldom works. We 
try to do that in cases when there is only one small word from a 
paragraph on a line.

Ideally, we don't want to do any adjustments at all. There are a lot of 
factors that make it necessary but fewer adjustments is better. Hope 
that helps!

Dennis

**Comment by Steven-Harris** [comment]
Oh ok! that's why it wasn't working!
I tried setting 1.2 = 2 and also 1.2 = -1 and I think you're right that Tex will not let that happen....

My only question is, can I make one specific verse change growth factor? If so, how would I go about doing it?

**Comment by Steven-Harris** [comment]
Sorry, I didn't mean to close the issue just yet

**Comment by thresherdj** [comment]
No, these adjustments are made only at the paragraph level not individual verses in a paragraph. Specifying the verse is for targeting purposes only and the whole paragraph will stretch. If you specified more than one verse in a paragraph the rendering engine would only use the first one, I think, but I can't recall if I've ever tried that.

**Comment by Steven-Harris** [comment]
So if I did 1.5 = 1 it should allow for the first paragraph to expand by a
factor of 1?

**Comment by thresherdj** [comment]
I wouldn't say "factor" I would say "line" as in make the paragraph take up one more line on the page, or column if it is a two column layout.

**Comment by Steven-Harris** [comment]
In the project.config. Does the cidlist have to be a three letter acronym and a book of the bible? I having trouble doing a custom one. I have gotten mat and mrk to work successfully.

**Comment by thresherdj** [comment]
Yes, it does. The reason why is that the macro package that drives the rendering engine is pretty much hard-coded to follow standard USFM Bible book references. so there's not much we can do about that. There are designators for front and back matter (see the USFM specification for the correct designators). However, it's hard to get the macros to do some of the special formatting we need for this type of content. As such, I developed a way around it by just importing PDF files directly into the project. I can't remember if that capability was in the master branch or not, but it is in my development branch.

**Comment by Steven-Harris** [comment]
Would you happen to know what this error is?
`MSG - Install macro package: [usfmTex], Reinitialized
[usfmTex.conf]
Traceback (most recent call last):
  File "/usr/local/bin/rapuma", line 765, in <module>
    userArguments(parser.parse_args())
  File "/usr/local/bin/rapuma", line 523, in userArguments
    Project(pid, gid).renderGroup(cid_list, pages, override, save)
  File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/project.py", line 182, in renderGroup
    self.createGroup().render(self.gid, cidList, pages, override, save)
  File "/usr/local/lib/python2.7/dist-packages/rapuma/group/usfm.py", line 192, in render
    self.project.managers['usfm_' + self.renderer.capitalize()].run(gid, cidList, pages, override, save)
  File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 568, in run
    self.makeSettingsTexFile()
  File "/usr/local/lib/python2.7/dist-packages/rapuma/manager/xetex.py", line 382, in makeSettingsTexFile
    installedFonts = self.macPackConfig['Fonts'].keys()
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'Fonts'`

**Comment by thresherdj** [comment]
Yes, I have a good idea what is wrong here but it will take me a bit to explain it because this is a big part of Rapuma that I rewrote last year and I can hardly remember how it used to work. One important feature of Rapuma is that it does not use system fonts, each project must have a specific font installed into it. I use a kind of package model to do this. A font package contains font files and other related encoding data that the rendering engine will use. It is installed into a specific location in an individual project, not the general system. It has never been an easy resource for me to manage, though it is better now than in the version you are using. To help you, I need to know what font package are you using and how you installed it. I suspect it hasn't because Rapuma is looking for the "Fonts" section in the macro config file and it isn't there. Could you confirm if you installed a font into this particular project? If so, how did you do it?

**Comment by Steven-Harris** [comment]
I didn't install any fonts to the project before rendering. However, after getting that error and simply run the render command again, Rapuma generates the font folder and populates it with the font data. Then it can render properly.

**Comment by thresherdj** [comment]
Yes, and no. In that version the process was kind of automated and it defaulted to a useful font if you are rendering Latin script text. If you are rendering a non-Latin script language, it gets really confusing because a useless font gets installed into the system. In the current version the user must purposefully install the font package they want. Sounds like you got it going and it installed a useful font for you for this exercise.

**Comment by Steven-Harris** [comment]
What will we need to do to support multilingual support. Is it as simple as putting the right stuff in the projects font folder?

**Comment by thresherdj** [comment]
You could put the stuff in there your self, but you also would need to inject the right data into the config file as well. The config data enables the renderer to use the right font in the right way. If you were to switch to the recent version all you would have to do is write a front-end GUI dialogue that drives the font install process which would do it all for you. Either way, you would need font packages for each script you work with.

**Comment by Steven-Harris** [comment]
Can you explain more of what you mean? By recent do you mean your branch?
Our goal is to give users full functionality of Rapuma from the web
application.

**Comment by thresherdj** [comment]
Yes, that would be my branch, the one we currently use for production.

**Comment by thresherdj** [comment]
Font information needs to be "fed" to TeX in a particular way. Rapuma processes everything based on the config files in a given project. In my branch I moved the font information from the macro config to a new font config file. This makes for a lot more flexibility.

**Comment by Steven-Harris** [comment]
Any reason it's not merged in to main yet? If I switch to your branch what
files should be required from the users and want config settings need to
entered?

**Comment by thresherdj** [comment]
I wanted to merge my branch into the master after it was tested but that's not my call as the code really doesn't really belong to me, technically. This would be SIL's call, I'm just a volunteer at this point.

**Comment by thresherdj** [comment]
I tried to communicate the need for a merge but I guess I wasn't successful. :-(

**Comment by Steven-Harris** [comment]
Oh ok!

**Comment by thresherdj** [comment]
If you merge at this point the CLI will be much different than what it is now. If you are under a time constraint, you may not want to do that this time around. If you have the time, and the merge was approved, I'd be happy to help anyway I can. Plus, we could probably share test projects more easily and I could help you debug easier.

**Comment by Steven-Harris** [comment]
Well I will switch to your branch as it appears it will be more robust to
use. And we can go from there

We haven't made a lot of integration with the CLI yet so I switch can still
be made. In addition, we are planning to use the CLI as little as possible
as it might be easier to deal with in the web app.

**Comment by thresherdj** [comment]
Ok. hopefully the learning curve will not be so bad and you will find the CLI more intuitive. Once you see how it works, you can probably reverse-engineer much of the CLI in the web app. I really feel that the current project config set up is more scalable than before and should support a lot of interaction with a GUI. Less is hard-coded in my branch compared to the master branch which should make it more robust.

**Comment by Steven-Harris** [comment]
Sweet! This looks a lot easier to use. Could you give me a list of some possible commands that should work? Although the help menu is way easier to understand, I am not sure what possible values I can enter for some of the arguments such as [Section, Key, and Value]. I just need a little help getting the ball rolling. Thanks!

**Comment by Steven-Harris** [comment]
right off the bat I tried, `rapuma asset add -g NEW_TEST -c usfm -p ~/src/web-scriptureforge/Publishing/NEW_TEST/Component/mat/` but I must be missing something and I probably need to setup my publishing folder location first

**Comment by thresherdj** [comment]
First, I would recommend that we close this thread and open a new one for the little tutorial that is to follow. After that, take a look in rapuma/resource/example/KYUM_ExampleAndTotorial.odt. I propose that we work through that example together in the user environment that Rapuma is used in right now. Once that has been done (which shouldn't take long) you can transfer that to the server environment, and that shouldn't be too hard. Once you have transferred it and run it in with the CLI on the server, I think it shouldn't be hard for you to figure out how to link in the web interface. Let me know how you want to proceed.

**Comment by Steven-Harris** [comment]
Great! Sounds like a plan. Thank you, Dennis!

**Comment by mhosken** [comment]
Dear Dennis,

> I wanted to merge my branch into the master after it was tested but that's not my call as the code really doesn't really belong to me, technically. This would be SIL's call, I'm just a volunteer at this point.

In as much as I have sufficient authority. I hereby authorise you to merge any code you see fit as being good for master, into master.

Now having said that. Because your change is not backwardly compatibly, I suggest you branch master as it is now into a version branch or at least tag it with a version tag before you do the merge, so that people can get back to the current CLI should they want to. Hmm. Tagging is fine, then someone can branch from the tag if they want to do more changes on that branch.

GB,
Martin

**Comment by thresherdj** [comment]
Thanks Martin, however, I am but a humble volunteer (who works with automotive issues all day long) and if I try this, I might do more harm than good. This may be a bit beyond my pay grade. :-) Would you mind merging or tagging a new branch for the cause? Also, Chris and Cambell might want to weigh in on this as well. Regardless, I feel uncomfortable trying this on my own. Thanks!
